ebean:
  # Name der Standarddatenbank
  db:
    # Datenquelle konfigurieren
    datasource:
      username: root   # Benutzername für die Datenbank
      password: ""     # Passwort für die Datenbank (leer lassen, falls nicht erforderlich)
      url: jdbc:mysql://localhost:3306/database  # URL der MySQL-Datenbank
      driver: com.mysql.cj.jdbc.Driver  # JDBC-Treiber für MySQL

    # Automatische Generierung und Ausführung von DDL (Tabellenerstellung)
    ddl:
      generate: true   # Automatisch DDL (Tabellen) generieren
      run: true        # DDL beim Starten ausführen (Tabellen erstellen)

    # Debug-Einstellungen, um die ausgeführten SQL-Befehle zu sehen
    debug:
      sql: true        # SQL-Befehle in den Logs anzeigen

    # Weitere Datenbankeinstellungen (optional)
    # minConnections: 2
    # maxConnections: 100
    # isolationLevel: READ_COMMITTED
